version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      # - 8080:8080
      - 8081:50000
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  nginx_proxy:
    container_name: nginx_proxy
    hostname: nginx_proxy
    image: nginx
    restart: always
    privileged: true
    user: root
    ports:
      # - 8082:80
      - 8080:8080
    links:
      - jenkins
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/cert:/etc/ssl/certs